name: CI/CD Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar Dependências do Sistema
      run: sudo apt-get install -y python3-tk

    - name: Instalar Dependências Python
      run: pip install -r requirements.txt

    - name: Testar Código
      run: python -m unittest discover

    - name: Verificar Qualidade do Código com Flake8
      run: flake8

