name: CI/CD Workflow

# Controle de gatilhos para execução do workflow
on:
  # Executa o workflow em push ou pull request para a branch "main"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Permite executar manualmente a partir da aba Actions
  workflow_dispatch:

# Define os jobs do workflow
jobs:
  # Job de build e teste
  build:
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest

    # Passos para o job
    steps:
      # Checkout do repositório
      - name: Checkout do Código
        uses: actions/checkout@v4

      # Configuração do Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Define a versão do Python que o projeto utiliza

      # Instalar dependências do projeto
      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Verificar qualidade do código com Flake8
      - name: Verificar Qualidade do Código
        run: |
          pip install flake8
          flake8 .

      # Executar testes (caso existam)
      - name: Executar Testes
        run: |
          pytest

      # Mensagem personalizada
      - name: Finalizar Build
        run: echo "Workflow de CI/CD finalizado com sucesso!"
