# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Instalar Dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb
        pip install -r requirements.txt

    - name: Testar Código
      run: |
        xvfb-run --auto-servernum python -m unittest discover

    - name: Verificar Qualidade do Código com Flake8
      run: |
        pip install flake8
        flake8 --max-line-length=120 --exclude=.venv

    - name: Finalizar Build
      run: echo "Build e testes finalizados com sucesso!"
